name: release

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }} 
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' && github.event.workflow_run.conclusion == 'success'
    steps:
    - uses: actions/checkout@v4
      with:
        ref: 'main'
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v3
      with:
        github_token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        workflow: build.yml
        name: mercari-enhancement-suite-artifacts
    - name: get-npm-version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@main
    - uses: ncipollo/release-action@v1
      with:
        artifactErrorsFailBuild: true
        tag: v${{ steps.package-version.outputs.current-version }}
        artifacts: "*.zip"
        token: ${{ secrets.YOUR_GITHUB_TOKEN }}
        body: "This extension will need to be loaded unpacked in developer mode:


1. Download `mercari-enhancement-suite.zip` and extract the `dist` directory somewhere

2. Follow these instructions to load: https://developer.chrome.com/docs/extensions/mv3/getstarted/#unpacked


Will work on Microsoft Edge as well."
    - name: Webhook
      uses: joelwmale/webhook-action@master
      with:
        url: ${{ secrets.WEBHOOK_URL }}
        headers: '{"content-type": "application/x-www-form-urlencoded", "cache-control": "no-cache"}'
        body: '{"api_key":"${{ secrets.WEBHOOK_API }}", "format": "json", "id": "792387595", "keyword_value": "r-v${{ steps.package-version.outputs.current-version}}"}'